<?php 

  if((stristr($text, 'A') OR stristr($text, 'B') OR stristr($text, 'V') OR stristr($text, 'G') OR stristr($text, 'D') OR stristr($text, 'E') OR stristr($text, 'Z') OR stristr($text, 'I') OR stristr($text, 'K') OR stristr($text, 'L') OR stristr($text, 'M') OR stristr($text, 'N') OR stristr($text, 'O') OR stristr($text, 'P') OR stristr($text, 'R') OR stristr($text, 'S') OR stristr($text, 'T') OR stristr($text, 'U') OR stristr($text, 'F') OR stristr($text, 'a') OR stristr($text, 'b') OR stristr($text, 'v') OR stristr($text, 'g') OR stristr($text, 'd') OR stristr($text, 'e') OR stristr($text, 'z') OR stristr($text, 'i') OR stristr($text, 'k') OR stristr($text, 'l') OR stristr($text, 'm') OR stristr($text, 'n') OR stristr($text, 'o') OR stristr($text, 'p') OR stristr($text, 'r') OR stristr($text, 's') OR stristr($text, 't') OR stristr($text, 'u') OR stristr($text, 'f')) == TRUE)
{$zwischenablage = "1";} 
else 
{$zwischenablage = "0";}

  if(stristr($text, 'Й') OR stristr($text, 'Ц') OR stristr($text, 'У') OR stristr($text, 'К') OR stristr($text, 'Е') OR stristr($text, 'Н') OR stristr($text, 'Г') OR stristr($text, 'Ш') OR stristr($text, 'Щ') OR stristr($text, 'З') OR stristr($text, 'Х') OR stristr($text, 'Ъ') OR stristr($text, 'Ф') OR stristr($text, 'Ы') OR stristr($text, 'В') OR stristr($text, 'А') OR stristr($text, 'П') OR stristr($text, 'Р') OR stristr($text, 'О') OR stristr($text, 'Л') OR stristr($text, 'Д') OR stristr($text, 'Ж') OR stristr($text, 'Э') OR stristr($text, 'Я') OR stristr($text, 'Ч') OR stristr($text, 'С') OR stristr($text, 'М') OR stristr($text, 'И') OR stristr($text, 'Т') OR stristr($text, 'Ь') OR stristr($text, 'Б') OR stristr($text, 'Ю') OR stristr($text, 'й') OR stristr($text, 'ц') OR stristr($text, 'у') OR stristr($text, 'к') OR stristr($text, 'е') OR stristr($text, 'н') OR stristr($text, 'г') OR stristr($text, 'ш') OR stristr($text, 'щ') OR stristr($text, 'з') OR stristr($text, 'х') OR stristr($text, 'ъ') OR stristr($text, 'ф') OR stristr($text, 'ы') OR stristr($text, 'в') OR stristr($text, 'а') OR stristr($text, 'п') OR stristr($text, 'р') OR stristr($text, 'о') OR stristr($text, 'л') OR stristr($text, 'д') OR stristr($text, 'ж') OR stristr($text, 'э') OR stristr($text, 'я') OR stristr($text, 'ч') OR stristr($text, 'с') OR stristr($text, 'м') OR stristr($text, 'и') OR stristr($text, 'т') OR stristr($text, 'ь') OR stristr($text, 'б') OR stristr($text, 'ю') OR stristr($text, 'ё') OR stristr($text, 'Ё') OR stristr($text, 'ҁ') OR stristr($text, 'є') OR stristr($text, 'ѕ') OR stristr($text, 'і') OR stristr($text, 'ї') OR stristr($text, 'ѡ') OR stristr($text, 'ѣ') OR stristr($text, 'ѥ') OR stristr($text, 'ѧ') OR stristr($text, 'ѩ') OR stristr($text, 'ѫ') OR stristr($text, 'ѭ') OR stristr($text, 'ѯ') OR stristr($text, 'ѱ') OR stristr($text, 'ѳ') OR stristr($text, 'ѵ') OR stristr($text, 'ѷ') OR stristr($text, 'ѹ') OR stristr($text, 'ѻ') OR stristr($text, 'ѽ') OR stristr($text, 'ѿ') OR stristr($text, 'ꙋ') OR stristr($text, 'ꙗ') OR stristr($text, 'ꙓ') OR stristr($text, 'ꙃ') OR stristr($text, 'ꙁ') OR stristr($text, 'Ҁ') OR stristr($text, 'Є') OR stristr($text, 'Ѕ') OR stristr($text, 'І') OR stristr($text, 'Ї') OR stristr($text, 'Ѡ') OR stristr($text, 'Ѣ') OR stristr($text, 'Ѥ') OR stristr($text, 'Ѧ') OR stristr($text, 'Ѩ') OR stristr($text, 'Ѫ') OR stristr($text, 'Ѭ') OR stristr($text, 'Ѯ') OR stristr($text, 'Ѱ') OR stristr($text, 'Ѳ') OR stristr($text, 'Ѵ') OR stristr($text, 'Ѷ') OR stristr($text, 'Ѹ') OR stristr($text, 'Ѻ') OR stristr($text, 'Ѽ') OR stristr($text, 'Ѿ') OR stristr($text, 'Ꙋ') OR stristr($text, 'Ꙗ') OR stristr($text, 'Ꙓ') OR stristr($text, 'Ꙃ') OR stristr($text, 'Ꙁ') == TRUE) {
    $eingabekodierung = "kyrillisch";}

  elseif((stristr($text, '͡') OR stristr($text, 'ō') OR stristr($text,'Ō') OR stristr($text, 'ǫ') OR stristr($text,'Ǫ')OR stristr($text, 'ę') OR stristr($text, 'Ę')OR stristr($text, 'ė') OR stristr($text, 'Ė') OR stristr($text, 'ĭ') OR stristr($text, 'Ĭ') OR stristr($text,'ī') OR stristr($text, 'Ī') OR stristr($text,'ḟ')OR stristr($text, 'Ḟ') OR stristr($text, 'ỳ')OR stristr($text, 'Ỳ') OR stristr($text, 'ẏ') OR stristr($text, 'Ẏ') OR stristr($text, 'ë') OR stristr($text, 'Ë') == TRUE) AND (stristr($text,'J') == FALSE) AND (stristr($text,'j') == FALSE) AND (stristr($text,'X') == FALSE) AND (stristr($text,'x') == FALSE) AND (stristr($text,'Ya') == FALSE) AND (stristr($text,'ya') == FALSE) AND (stristr($text,'YA') == FALSE) AND (stristr($text,'Yu') == FALSE) AND (stristr($text,'yu') == FALSE) AND (stristr($text,'YU') == FALSE) AND (stristr($text, 'Â') == FALSE) AND (stristr($text, 'â') == FALSE) AND (stristr($text, 'Ǎ') == FALSE) AND (stristr($text,'ǎ') == FALSE) AND (stristr($text, 'Č') == FALSE) AND (stristr($text, 'č') == FALSE) AND (stristr($text, 'Ẽ') == FALSE) AND (stristr($text, 'ẽ') == FALSE) AND (stristr($text, 'Ě') == FALSE) AND (stristr($text, 'ě') == FALSE) AND (stristr($text, 'È') == FALSE) AND (stristr($text, 'è') == FALSE) AND (stristr($text, 'Ê') == FALSE) AND (stristr($text,'ê') == FALSE) AND (stristr($text, 'Ì') == FALSE) AND (stristr($text, 'ì') == FALSE) AND (stristr($text,'Ï') == FALSE) AND (stristr($text, 'ï') == FALSE) AND (stristr($text, 'Õ') == FALSE) AND (stristr($text,'õ') == FALSE) AND (stristr($text, 'Ô') == FALSE) AND (stristr($text, 'ô') == FALSE) AND (stristr($text,'Š') == FALSE) AND (stristr($text, 'š') == FALSE) AND (stristr($text, 'Ŝ') == FALSE) AND (stristr($text,'ŝ') == FALSE) AND (stristr($text, 'Û') == FALSE) AND (stristr($text, 'û') == FALSE) AND (stristr($text,'Ẑ') == FALSE) AND (stristr($text, 'ẑ') == FALSE) AND (stristr($text, 'Ž') == FALSE) AND (stristr($text,'ž') == FALSE) AND ($zwischenablage == "1")){
    $eingabekodierung = "alalc";}
	
  elseif((stristr($text, 'Č') OR stristr($text, 'X') OR stristr($text, 'x') OR stristr($text, 'č') OR stristr($text, 'Ẽ') OR stristr($text, 'ẽ') OR stristr($text, 'Ë') OR stristr($text, 'ë') OR stristr($text, 'Ę') OR stristr($text, 'ę') OR stristr($text, 'È') OR stristr($text, 'è') OR stristr($text, 'Ě') OR stristr($text, 'ě') OR stristr($text, 'Ḟ') OR stristr($text, 'ḟ') OR stristr($text, 'Õ') OR stristr($text, 'õ') OR stristr($text, 'Ō') OR stristr($text, 'ō') OR stristr($text, 'Ô') OR stristr($text, 'ô') OR stristr($text, 'Ǫ') OR stristr($text, 'ǫ') OR stristr($text, 'Š') OR stristr($text, 'š') OR stristr($text, 'Ẏ') OR stristr($text, 'ẏ') OR stristr($text, 'Ž') OR stristr($text, 'ž') == TRUE) AND (stristr($text,'H') == FALSE) AND (stristr($text,'h') == FALSE) AND (stristr($text,'Ya') == FALSE) AND (stristr($text,'ya') == FALSE) AND (stristr($text,'YA') == FALSE) AND (stristr($text,'Yu') == FALSE) AND (stristr($text,'yu') == FALSE) AND (stristr($text,'YU') == FALSE) AND (stristr($text, 'Ẽ') == FALSE) AND (stristr($text, 'ẽ') == FALSE) AND (stristr($text, 'Ė') == FALSE) AND (stristr($text,'ė') == FALSE) AND (stristr($text, 'Ę') == FALSE) AND (stristr($text, 'Ė') == FALSE) AND (stristr($text, 'ė') == FALSE) AND (stristr($text, 'Ï') == FALSE) AND (stristr($text,'ï') == FALSE) AND (stristr($text, 'Ĭ') == FALSE) AND (stristr($text, 'ĭ') == FALSE) AND (stristr($text,'Ī') == FALSE) AND (stristr($text, 'ī') == FALSE) AND (stristr($text, 'Â') == FALSE) AND (stristr($text,'â') == FALSE) AND (stristr($text, 'Ǎ') == FALSE) AND (stristr($text, 'ǎ') == FALSE) AND (stristr($text,'Ê') == FALSE) AND (stristr($text, 'ê') == FALSE) AND (stristr($text, 'Ì') == FALSE) AND (stristr($text,'ì') == FALSE) AND (stristr($text, 'Ŝ') == FALSE) AND (stristr($text, 'ŝ') == FALSE) AND (stristr($text,'Û') == FALSE) AND (stristr($text, 'û') == FALSE) AND (stristr($text, 'Ỳ') == FALSE) AND (stristr($text,'ỳ') == FALSE) AND (stristr($text, 'Ẑ') == FALSE) AND (stristr($text, 'ẑ') == FALSE) AND (stristr($text,'͡') == FALSE) AND ($zwischenablage == "1")){
    $eingabekodierung = "wissenschaftlich";}
	
  elseif((stristr($text, 'Č') OR stristr($text, 'č') OR stristr($text, 'Ẽ') OR stristr($text, 'ẽ') OR stristr($text, 'Ë') OR stristr($text, 'ë') OR stristr($text, 'Ė') OR stristr($text, 'ė') OR stristr($text, 'Ę') OR stristr($text, 'ę') OR stristr($text, 'Ě') OR stristr($text, 'ě') OR stristr($text, 'Ḟ') OR stristr($text, 'ḟ') OR stristr($text, 'Ï') OR stristr($text, 'ï') OR stristr($text, 'Ĭ') OR stristr($text, 'ĭ') OR stristr($text, 'Ī') OR stristr($text, 'ī') OR stristr($text, 'Õ') OR stristr($text, 'õ') OR stristr($text, 'Ǫ') OR stristr($text, 'ǫ') OR stristr($text, 'Ō') OR stristr($text, 'ō') OR stristr($text, 'Ô') OR stristr($text, 'ô') OR stristr($text, 'Š') OR stristr($text, 'š') OR stristr($text, 'Ẏ') OR stristr($text, 'ẏ') OR stristr($text, 'Ž') OR stristr($text, 'ž') == TRUE) AND (stristr($text,'X') == FALSE) AND (stristr($text,'x') == FALSE) AND (stristr($text, 'Â') == FALSE) AND (stristr($text, 'â') == FALSE) AND (stristr($text, 'Ǎ') == FALSE) AND (stristr($text, 'ǎ') == FALSE) AND (stristr($text,'È') == FALSE) AND (stristr($text, 'è') == FALSE) AND (stristr($text, 'Ê') == FALSE) AND (stristr($text, 'ê') == FALSE) AND (stristr($text,'Ì') == FALSE) AND (stristr($text, 'ì') == FALSE) AND (stristr($text, 'Ŝ') == FALSE) AND (stristr($text, 'ŝ') == FALSE) AND (stristr($text,'Û') == FALSE) AND (stristr($text, 'û') == FALSE) AND (stristr($text, 'Ỳ') == FALSE) AND (stristr($text, 'ỳ') == FALSE) AND (stristr($text,'Ẑ') == FALSE) AND (stristr($text, 'ẑ') == FALSE) AND (stristr($text, '͡') == FALSE) AND ($zwischenablage == "1")){
    $eingabekodierung = "isor9";}
	
  elseif((stristr($text, 'Â') OR stristr($text, 'â') OR stristr($text, 'Ǎ') OR stristr($text, 'ǎ') OR stristr($text, 'Č') OR stristr($text, 'č') OR stristr($text, 'Ë') OR stristr($text, 'ë') OR stristr($text, 'È') OR stristr($text, 'è') OR stristr($text, 'Ě') OR stristr($text, 'ě') OR stristr($text, 'Ê') OR stristr($text, 'ê') OR stristr($text, 'Ì') OR stristr($text, 'ì') OR stristr($text, 'Ō') OR stristr($text, 'ō') OR stristr($text, 'Š') OR stristr($text, 'š') OR stristr($text, 'Ŝ') OR stristr($text, 'ŝ') OR stristr($text, 'Û') OR stristr($text, 'û') OR stristr($text, 'Ỳ') OR stristr($text, 'ỳ') OR stristr($text, 'Ẑ') OR stristr($text, 'ẑ') OR stristr($text, 'Ž') OR stristr($text, 'ž') == TRUE) AND (stristr($text,'X') == FALSE) AND (stristr($text,'x') == FALSE) AND (stristr($text,'Ya') == FALSE) AND (stristr($text,'ya') == FALSE) AND (stristr($text,'YA') == FALSE) AND (stristr($text,'Yu') == FALSE) AND (stristr($text,'yu') == FALSE) AND (stristr($text,'YU') == FALSE) AND (stristr($text, 'Ẽ') == FALSE) AND (stristr($text, 'ẽ') == FALSE) AND (stristr($text, 'Ė') == FALSE) AND (stristr($text,'ė') == FALSE) AND (stristr($text, 'Ę') == FALSE) AND (stristr($text, 'ę') == FALSE) AND (stristr($text,'Ḟ') == FALSE) AND (stristr($text, 'ḟ') == FALSE) AND (stristr($text, 'Ï') == FALSE) AND (stristr($text,'ï') == FALSE) AND (stristr($text, 'Ĭ') == FALSE) AND (stristr($text, 'ĭ') == FALSE) AND (stristr($text,'Ī') == FALSE) AND (stristr($text, 'ī') == FALSE) AND (stristr($text, 'Õ') == FALSE) AND (stristr($text,'õ') == FALSE) AND (stristr($text, 'Ǫ') == FALSE) AND (stristr($text, 'ǫ') == FALSE) AND (stristr($text,'Ô') == FALSE) AND (stristr($text, 'ô') == FALSE) AND (stristr($text, 'Ẏ') == FALSE) AND (stristr($text,'ẏ') == FALSE) AND (stristr($text, '͡') == FALSE) AND ($zwischenablage == "1")){
    $eingabekodierung = "iso9";}
		
  elseif((stristr($text, 'Shh') OR stristr($text, 'shh') OR stristr($text, 'SHH') OR stristr($text, 'X') OR stristr($text, 'x') OR stristr($text, "E\\'") OR stristr($text, "e\\'") OR stristr($text, "Y\\'") OR stristr($text, "y\\'") OR stristr($text, "I\\'") OR stristr($text, "i\\'") OR stristr($text, "O\\'") OR stristr($text, "o\\'") OR stristr($text, 'CZ') OR stristr($text, 'Cz') OR stristr($text, 'cz') == TRUE) AND ($zwischenablage == "1")){
    $eingabekodierung = "gost779b";}

  elseif((stristr($text, 'Č') == FALSE) AND (stristr($text, 'č') == FALSE) AND (stristr($text, 'Ẽ') == FALSE) AND (stristr($text, 'ẽ') == FALSE) AND (stristr($text, 'Ë') == FALSE) AND (stristr($text, 'ë') == FALSE) AND (stristr($text, 'Ę') == FALSE) AND (stristr($text, 'ę') == FALSE) AND (stristr($text, 'È') == FALSE) AND (stristr($text, 'è') == FALSE) AND (stristr($text, 'Ě') == FALSE) AND (stristr($text, 'ě') == FALSE) AND (stristr($text, 'Ḟ') == FALSE) AND (stristr($text, 'ḟ') == FALSE) AND (stristr($text, 'Õ') == FALSE) AND (stristr($text, 'õ') == FALSE) AND (stristr($text, 'Ō') == FALSE) AND (stristr($text, 'ō') == FALSE) AND (stristr($text, 'Ô') == FALSE) AND (stristr($text, 'ô') == FALSE) AND (stristr($text, 'Ǫ') == FALSE) AND (stristr($text, 'ǫ') == FALSE) AND (stristr($text, 'Š') == FALSE) AND (stristr($text, 'š') == FALSE) AND (stristr($text, 'Ẏ') == FALSE) AND (stristr($text, 'ẏ') == FALSE) AND (stristr($text, 'Ž') == FALSE) AND (stristr($text, 'ž') == FALSE) AND (stristr($text, 'H') == FALSE) AND (stristr($text, 'h') == FALSE) AND (stristr($text, 'X') == FALSE) AND (stristr($text, 'x') == FALSE) AND (stristr($text, 'J') == FALSE) AND (stristr($text, 'j') == FALSE) AND (stristr($text, 'Ẽ') == FALSE) AND (stristr($text, 'ẽ') == FALSE) AND (stristr($text, 'Ė') == FALSE) AND (stristr($text, 'ė') == FALSE) AND (stristr($text, 'Ę') == FALSE) AND (stristr($text, 'Ė') == FALSE) AND (stristr($text, 'ė') == FALSE) AND (stristr($text, 'Ï') == FALSE) AND (stristr($text, 'ï') == FALSE) AND (stristr($text, 'Ĭ') == FALSE) AND (stristr($text, 'ĭ') == FALSE) AND (stristr($text, 'Ī') == FALSE) AND (stristr($text, 'ī') == FALSE) AND (stristr($text, 'Â') == FALSE) AND (stristr($text, 'â') == FALSE) AND (stristr($text, 'Ǎ') == FALSE) AND (stristr($text, 'ǎ') == FALSE) AND (stristr($text, 'Ê') == FALSE) AND (stristr($text, 'ê') == FALSE) AND (stristr($text, 'Ì') == FALSE) AND (stristr($text, 'ì') == FALSE) AND (stristr($text, 'Ŝ') == FALSE) AND (stristr($text, 'ŝ') == FALSE) AND (stristr($text, 'Û') == FALSE) AND (stristr($text, 'û') == FALSE) AND (stristr($text, 'Ỳ') == FALSE) AND (stristr($text, 'ỳ') == FALSE) AND (stristr($text, 'Ẑ') == FALSE) AND (stristr($text, 'ẑ') == FALSE) AND (stristr($text, '͡') == FALSE) AND (stristr($text, 'Ya') == FALSE) AND (stristr($text, 'ya') == FALSE) AND (stristr($text, 'YA') == FALSE) AND (stristr($text, 'Yu') == FALSE) AND (stristr($text, 'yu') == FALSE) AND (stristr($text, 'YU') == FALSE) AND (stristr($text, 'Q') == FALSE) AND (stristr($text, 'q') == FALSE) AND (stristr($text, 'W') == FALSE) AND (stristr($text, 'w') == FALSE) AND ($zwischenablage == "1")){
    $eingabekodierung = "unbestimmt";}
	
	else{
	$eingabekodierung = "translit";}
	?>