<?php
$buchstaben = $text;
	$text = preg_replace('{(?<=[ЦКНГШЩЗХФВПРЛДЖЧСМИТБцкнгшщзхфвпрлджчсмтб])Е}','E', $text);
	$text = preg_replace('{(?<=[ЦКНГШЩЗХФВПРЛДЖЧСМИТБцкнгшщзхфвпрлджчсмтб])е}','e', $text);
	$text = preg_replace('{(?:^|(?<=[аийоуыеeёАИЙОУЫЕЁЬьЪъ]))Е}','Ye', $text);
	$text = preg_replace('{(?:^|(?<=[аийоуыеeёАИЙОУЫЕЁЬьЪъ]))е}','ye', $text);
	$text = preg_replace('{(?:^|(?<=[аийоуыеeёАИЙОУЫЕЁЬьЪъ]))Ё}','Yë', $text);
	$text = preg_replace('{(?:^|(?<=[аийоуыеeёАИЙОУЫЕЁЬьЪъ]))ё}','yë', $text);
	$text = preg_replace('{(?<=[ЦКНГШЩЗХФВПРЛДЖЧСМИТБцкнгшщзхфвпрлджчсмтб])Ѣ}','E', $text);
	$text = preg_replace('{(?<=[ЦКНГШЩЗХФВПРЛДЖЧСМИТБцкнгшщзхфвпрлджчсмтб])ѣ}','e', $text);
	$text = preg_replace('{(?:^|(?<=[аийоуыеeёАИЙОУЫЕЁЬьЪъ]))Ѣ}','Ye', $text);
	$text = preg_replace('{(?:^|(?<=[аийоуыеeёАИЙОУЫЕЁЬьЪъ]))ѣ}','ye', $text);
    $text = str_replace('Й', 'Y', $text);
    $text = str_replace('й', 'y', $text);
    $text = str_replace('А', 'A', $text);
    $text = str_replace('Б', 'B', $text);
    $text = str_replace('В', 'V', $text);
    $text = str_replace('Г', 'G', $text);
    $text = str_replace('Д', 'D', $text);
    $text = str_replace('Е', 'E', $text);
    $text = str_replace('Ё', 'Ë', $text);
    $text = str_replace('Ж', 'Zh', $text);
    $text = str_replace('З', 'Z', $text);
    $text = str_replace('И', 'I', $text);
    $text = str_replace('К', 'K', $text);
    $text = str_replace('Л', 'L', $text);
    $text = str_replace('М', 'M', $text);
    $text = str_replace('Н', 'N', $text);
    $text = str_replace('О', 'O', $text);
    $text = str_replace('П', 'P', $text);
    $text = str_replace('Р', 'R', $text);
    $text = str_replace('С', 'S', $text);
    $text = str_replace('Т', 'T', $text);
    $text = str_replace('У', 'U', $text);
    $text = str_replace('Ф', 'F', $text);
    $text = str_replace('Х', 'Kh', $text);
    $text = str_replace('Ц', 'Ts', $text);
    $text = str_replace('Ч', 'Ch', $text);
    $text = str_replace('Ш', 'Sh', $text);
    $text = str_replace('Щ', 'Shch', $text);
    $text = str_replace('Ъ', '"', $text);
    $text = str_replace('Ь', '\'', $text);
    $text = str_replace('Ю', 'Yu', $text);
    $text = str_replace('Я', 'Ya', $text);
    $text = str_replace('Ы', 'Y', $text);
    $text = str_replace('Э', 'E', $text);
    $text = str_replace('а', 'a', $text);
    $text = str_replace('б', 'b', $text);
    $text = str_replace('в', 'v', $text);
    $text = str_replace('г', 'g', $text);
    $text = str_replace('д', 'd', $text);
    $text = str_replace('е', 'e', $text);
	$text = str_replace('ё', 'ë', $text);
    $text = str_replace('ж', 'zh', $text);
    $text = str_replace('з', 'z', $text);
    $text = str_replace('и', 'i', $text);
    $text = str_replace('к', 'k', $text);
    $text = str_replace('л', 'l', $text);
    $text = str_replace('м', 'm', $text);
    $text = str_replace('н', 'n', $text);
    $text = str_replace('о', 'o', $text);
    $text = str_replace('п', 'p', $text);
    $text = str_replace('р', 'r', $text);
    $text = str_replace('с', 's', $text);
    $text = str_replace('т', 't', $text);
    $text = str_replace('у', 'u', $text);
    $text = str_replace('ф', 'f', $text);
    $text = str_replace('х', 'kh', $text);
    $text = str_replace('ц', 'ts', $text);
    $text = str_replace('ч', 'ch', $text);
    $text = str_replace('ш', 'sh', $text);
    $text = str_replace('щ', 'shch', $text);
    $text = str_replace('ь', '\'', $text);
    $text = str_replace('ю', 'yu', $text);
    $text = str_replace('я', 'ya', $text);
    $text = str_replace('ы', 'y', $text);
    $text = str_replace('э', 'e', $text);
    $text = str_replace('ъ', '"', $text);

    $text = str_replace('І', 'I', $text);
    $text = str_replace('Ѳ', 'F', $text);
    $text = str_replace('Ѵ', 'I', $text);
    $text = str_replace('Є', 'E', $text);
    $text = str_replace('Ѕ', 'S', $text);
    $text = str_replace('Ѡ', 'O', $text);
    $text = str_replace('Ѥ', 'Ye', $text);
    $text = str_replace('Ѧ', 'Ya', $text);
    $text = str_replace('Ѩ', 'Ya', $text);
	$text = preg_replace('{Ѫ(?=[. ,;:\\\/\[\]\"»«])|Ѫ$|Ѫ\s}','', $text);
    $text = str_replace('Ѫ', 'U', $text);
    $text = str_replace('Ѭ', 'Yu', $text);
    $text = str_replace('Ѯ', 'Ks', $text);
    $text = str_replace('Ѱ', 'Ps', $text);
    $text = str_replace('Ꙃ', 'S', $text);
    $text = str_replace('Ꙁ', 'Z', $text);
    $text = str_replace('Ꙋ', 'U', $text);
    $text = str_replace('Ѹ', 'U', $text);
    $text = str_replace('Ꙑ', 'Y', $text);
    $text = str_replace('Ꙗ', 'Ya', $text);
    $text = str_replace('Ꙓ', 'Ye', $text);
    $text = str_replace('Ѷ', 'I', $text);
    $text = str_replace('Ѿ', 'Ot', $text);
    $text = str_replace('Ѻ', 'O', $text);
    $text = str_replace('Ҁ', '90', $text);
    $text = str_replace('і', 'i', $text);
	$text = str_replace('ѳ', 'f', $text);
    $text = str_replace('ѵ', 'i', $text);
    $text = str_replace('є', 'e', $text);
    $text = str_replace('ѕ', 's', $text);
    $text = str_replace('ѡ', 'o', $text);
    $text = str_replace('ѥ', 'ye', $text);
    $text = str_replace('ѧ', 'ya', $text);
    $text = str_replace('ѩ', 'ya', $text);
	$text = preg_replace('{ѫ(?=[. ,;:\\\/\[\]\"»«])|ѫ$|ѫ\s}','', $text);
    $text = str_replace('ѫ', 'u', $text);
    $text = str_replace('ѭ', 'yu', $text);
    $text = str_replace('ѯ', 'ks', $text);
    $text = str_replace('ѱ', 'ps', $text);
    $text = str_replace('ꙃ', 's', $text);
    $text = str_replace('ꙁ', 'z', $text);
    $text = str_replace('ꙋ', 'u', $text);
    $text = str_replace('ѹ', 'u', $text);
    $text = str_replace('ꙑ', 'y', $text);
    $text = str_replace('ꙗ', 'ya', $text);
    $text = str_replace('ꙓ', 'ye', $text);
    $text = str_replace('ѷ', 'i', $text);
    $text = str_replace('ѿ', 'ot', $text);
    $text = str_replace('ѻ', 'o', $text);
    $text = str_replace('ҁ', '90', $text);
    $text = str_replace('ї', 'i', $text);
    $text = str_replace('Ї', 'I', $text);
	$text = stripslashes($text);
  ?>